### ISSUE TITLE
Invalid Access Token

### ISSUE THREAD

**Issue by erazharahmad** [ziming/laravel-myinfo-sg#11]
I am getting invalid access token when trying to use myinfo-person route. 
{"message":"Invalid Access Token"}
Please help me on this.

**Comment by erazharahmad** [comment]
now i am getting error 
openssl_sign(): supplied key param cannot be coerced into a private key
can you please help to resolve it?

**Comment by ziming** [comment]
OS and PHP Version?

**Comment by ziming** [comment]
Closed due to non response.

**Comment by erazharahmad** [comment]
OS: windows 10
PHP: 7.3
Package Version: latest i downloaded.

**Comment by ziming** [comment]
Please upgrade to PHP 7.4 and at least Laravel 6 so you can update to the latest version of this package.

https://github.com/ziming/laravel-myinfo-sg/releases

**Comment by erazharahmad** [comment]
PHP Version 7.4.3
ziming/laravel-myinfo-sg:  2.1
Laravel Framework : 6.17.1

I updated php and laravel but still getting same error you can check attached screenshot. 

![image](https://user-images.githubusercontent.com/23446801/76183640-212e9380-61ef-11ea-81a3-cc40bfc2ba32.png)

**Comment by ziming** [comment]
Could I see the list of php extensions you have installed?

**Comment by erazharahmad** [comment]
Please check below list. Also if any extension is required please let me know. i will try to install. 
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
SPL
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]

**Comment by ziming** [comment]
Looks good to me so far. Did you publish the keys?

**Comment by erazharahmad** [comment]
currently i am using test API. sandbox is working fine but getting issue when i am trying to use test API. Demo keys should work for test API. 

[myinfo-ssl.zip](https://github.com/ziming/laravel-myinfo-sg/files/4305460/myinfo-ssl.zip)

**Comment by ziming** [comment]
If the Sandbox API is working for you, then my package is working.

If you have issues calling the staging or production APIs, check if you use the right certificates and keys.

I deleted your comment as you shouldn't be sharing your keys with me.

**Comment by erazharahmad** [comment]
i got certificates from myinfo but only public key is there. can you please help me how i can get its private key?

**Comment by ziming** [comment]
This is outside the scope of this package, it's best you consult govtech on certificates and keys matters.
