### ISSUE TITLE
verifyJWS return null

### ISSUE THREAD

**Issue by johnadvincula-ada** [ziming/laravel-myinfo-sg#17]
I got `InvalidAccessTokenException`when running `LaravelMyinfoSg::getMyinfoPersonData($code)` on tinker

I think this is the same issue as this https://github.com/ziming/laravel-myinfo-sg/issues/13

**Comment by ziming** [comment]
R u on the latest version of the package? It's working fine for me in production.

**Comment by johnadvincula-ada** [comment]
Hi @ziming yes im currently using "ziming/laravel-myinfo-sg": "^2.3"

**Comment by johnadvincula-ada** [comment]
this is the exact error I got 
![image](https://user-images.githubusercontent.com/89056034/148014913-2e240e65-e15a-479a-b84f-08e68147ab10.png)

**Comment by ziming** [comment]
what php extensions u have installed? and which php version r u on?

It's working for me on PHP 8.0

**Comment by johnadvincula-ada** [comment]
Im currently using PHP 7.4 and these are the extension enabled on my php.ini `curl,ftp,fileinfo,gd2,gmp,intl,mbstring,exif,openssl,pdo_mysql,sodium,xsl`

**Comment by ziming** [comment]
Your extensions look okay to me.

**Comment by johnadvincula-ada** [comment]
> Your extensions look okay to me so far.

Hi @ziming its working now on my local I can get the data using PKI signature, but when we deploy it on the laravel vapor we got the json with the content of ```{ message: Internal Server Error}``` have you encountered that?

**Comment by ziming** [comment]
Hmm. I have personally never used laravel vapor before. Does it work on a normal server setup?

**Comment by johnadvincula-ada** [comment]
> Hmm. I have personally never used laravel vapor before. Does it work on a normal server setup?

you mean the traditional setup using vps with manual installation of nginx / php?, We havent tried it yet

**Comment by ziming** [comment]
the traditional server setup yea.

it's working for me in production & I'm not in a serverless environment.

the latest error message you posted is quite vague so hard for me to guess what the issue might be.

**Comment by johnadvincula-ada** [comment]
Thank you @ziming for your time :) I already figured out the problem . its because of the request timeout in our server :) , by the way just a suggestion. instead of storing the certificate as file, you can put it on environtment variable instead :)

**Comment by mhanifazmi97** [comment]
Hi, I encountered the same error and I'm clueless what to check. Can you assist me? Please advise. Thank you
