### ISSUE TITLE
Response issue

### ISSUE THREAD

**Issue by aqshah20** [ziming/laravel-myinfo-sg#30]
![Screenshot_69](https://github.com/ziming/laravel-myinfo-sg/assets/22372156/da6ed423-4df3-41d8-81ac-881b103bdc62)
after submitting the form on this route : route('myinfo.singpass')  getting the error like 404 could you please guide me where is the problem?

**Comment by ziming** [comment]
Myinfo released a new major version called v4. This package has not been upgraded to support v4 yet.

Currently I don't have the time to upgrade this package for free as I'm working on other things that pays the bill. So you may have to wait or do it yourself for now.

**Comment by ziming** [comment]
I cannot guide u on something I have not done. sorry

**Comment by kvinothkumarr** [comment]
![image](https://github.com/ziming/laravel-myinfo-sg/assets/15259987/213db8c3-e9e3-4e22-8f04-78b7ff6963bc)
after redirect from consent form i got this error how to fix and get data of person. pls guide me.

**Comment by aqshah20** [comment]
DM me at jqsystech@gmail.com I can help you. I have done singpass integration.
