### ISSUE TITLE
file_get_contents(https://test.api.myinfo.gov.sg/com/v3/token): Failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized in G:\xampp\htdocs\callback.php on line 42 Token request failed

### ISSUE THREAD

**Issue by kvinothkumarr** [ziming/laravel-myinfo-sg#32]
![image](https://github.com/ziming/laravel-myinfo-sg/assets/15259987/84ac5272-8864-49df-92fe-2caf2fa802de)
after redirect from consent form got this error. how to solve this and get person data. pls guid me. iam new to this.

**Comment by ziming** [comment]
when u call the token api. make sure u pass everything that is needed

**Comment by kvinothkumarr** [comment]
Thanks for your response. Can I get the upgraded version (V4) with the V4 update?

**Comment by ziming** [comment]
I haven't got the time to get v4 out yet sorry. the sites I work on are still on v3 and my employer has more important piorities currently. you can still use v3 until April 2024
