### ISSUE TITLE
Person Data (JWE) Verify

### ISSUE THREAD

**Issue by ankitsinghdalal** [ziming/laravel-myinfo-sg#9]
$personDataJWS = MyInfoSecurityService::decryptJWE(
                    $personData,
                    config('laravel-myinfo-sg.private_key_path')
                );

This is the method which is unable to decrypt the personData.

**Comment by ziming** [comment]
Ah think I know why

Will email you the solution when I got back home.

In the mean time (share what's comfortable):

PHP Version?
Laravel Version?
Project used for?

Thanks!

**Comment by ziming** [comment]
Sent you the fix. Closing the issue.
